export const UPDATE_SLIDER_RANGE = 'UPDATE_SLIDER_RANGE';
export const UPDATE_CHECKBOX_TAGS = 'UPDATE_CHECKBOX_TAGS';
export const UPDATE_SELECT_SORT = 'UPDATE_SELECT_SORT';
export const UPDATE_PAGE = 'UPDATE_PAGE';
export const UPDATE_SEARCH_TEXT = 'UPDATE_SEARCH_TEXT';
export const RESET_FILTERS = 'RESET_FILTERS';

export const CHANGE_TOKEN = 'CHANGE_TOKEN';
export const CHANGE_ACCOUNT_ID = 'CHANGE_ACCOUNT_ID';
export const RESET_USER_CREDITS = 'RESET_USER_CREDITS';

export const LOAD_FILMS = 'LOAD_FILMS';
export const LOAD_GENRES = 'LOAD_GENRES';
export const LOAD_DETAILS = 'LOAD_DETAILS';
export const LOAD_CREDITS = 'LOAD_CREDITS';
export const LOAD_FAVORITE_LIST = 'LOAD_FAVORITE_LIST';

export const DELETE_FAVORITE_FILM = 'DELETE_FAVORITE_FILM';
export const ADD_FAVORITE_FILM = 'ADD_FAVORITE_FILM';